### User API requests
### User registration
POST http://localhost:5000/userApi/register
Content-Type: application/json

{
    "facultyId":"9",
    "email":"user@gmail.com",
    "contactNumber":"9999999999",
    "password":"admin",
    "approveStatus":0,
    "userType":"faculty"
}

### User login
POST http://localhost:5000/userApi/login
Content-Type: application/json

{
    "facultyId":9,
    "password":"admin"
}



